### PR TITLE
Added required files for Certificate Generator UI

### PR DESCRIPTION
**Pull request by Anushka-codergirl**

### CODE REVIEW

**Review by rohan-kulkarni-25 — COMMENTED** [review]
- Than adding a seperate html file we can handle this with help of javascript also

**Comment by praveenscience** [comment]
Hi @Anushka-codergirl, this is not exactly what was expected, but I'll have it here, so that you can update your PR after the initial demo has been added.

**Comment by praveenscience** [comment]
@Anushka-codergirl Check out the [last commit](https://github.com/praveenscience/Certificate-Generator-UI/commit/40e1e0f00a86026564603d2f07f1b0788c155f3c) or [this directory](https://github.com/praveenscience/Certificate-Generator-UI/tree/main/praveenscience).

**Comment by praveenscience** [comment]
@Anushka-codergirl Any updates on this?

**Comment by praveenscience** [comment]
Feel free to reopen when you're submitting it once again. 😁

**Comment by Anushka-codergirl** [comment]
Ya sure!

**Pull request closed without merging**
